version = 0.1

[default.global.parameters]
region = "ap-south-1"

[default.deploy.parameters]
stack_name = "wb-digital-sahayak"
resolve_s3 = true
resolve_image_repos = true
s3_prefix = "wb-digital-sahayak"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true 